#!/bin/sh

(

  source /home/noodle/.bash_profile
  
  cd $(dirname $0)
  
  args=()
  force=false
  
  while (( "$#" )); do
    case "$1" in
      -f) force=true; shift;;
      *) args=( "${args[@]}" "$1" ); shift;;
    esac
  done
  
  sdate=
	sfile=
  for f in ./*; do
    if [[ "$(basename $f)" == "$(basename $0)" ]] || [[ "$(basename $f)" == "server.lock" ]] || [[ "$(basename $f)" =~ ^(./)?std(err|out).log$ ]]; then
      continue
    fi
    ndate=$(mtime $f)
    if [[ $ndate > $sdate ]]; then
      sdate=$ndate
			sfile=$f
    fi
  done
  
  if [ -f server.lock ]; then
    ldate=$(mtime server.lock)
  fi
  
  if [[ $sdate > $ldate ]]; then
	  echo $sdate $ldate
		echo $sfile
    force=true
  fi
  
  if [ $force == true ]; then
    echo "reloading changes in server script"
    ps aux | grep noodlebot.js | grep -v grep | awk {'print $2'} | xargs kill -9
  fi
  
  if [[ $(ps aux | grep node | grep noodlebot.js -c) < 1 ]]; then
    echo "starting up noodlebot service noodlebot.js"
    node noodlebot.js &
    touch -m server.lock
  fi

)
